### 1.Convert Tuple to 


#### [a]List

In [39]:
#Initialising a tuple
Tuple_1 = ('I','am','Tuple','coverted','to','list')
print(Tuple_1)

#Type of object
print(type(Tuple_1))

#Converting to list
List_1= list(Tuple_1)
print(List_1)

#Type of object
print(type(List_1))

('I', 'am', 'Tuple', 'coverted', 'to', 'list')
<type 'tuple'>
['I', 'am', 'Tuple', 'coverted', 'to', 'list']
<type 'list'>


#### [b]Set

In [56]:
#Initialising a tuple
Tuple_2 = ('I','am','Tuple','coverted','to','set')
print(Tuple_2)

#Type of object
print(type(Tuple_2))

#Converting to set
Set_1 = set(Tuple_2)
print Set_1

#Type of object
print(type(Set_1))
Set_1

('I', 'am', 'Tuple', 'coverted', 'to', 'set')
<type 'tuple'>
set(['set', 'Tuple', 'I', 'am', 'to', 'coverted'])
<type 'set'>


{'I', 'Tuple', 'am', 'coverted', 'set', 'to'}

#### [c]Dictionary

In [54]:
#Initialising a tuple
Tuple_3 =(('I','am'),('Tuple','coverted'),('to','Dictionary'))
print(Tuple_3)

#Type of object
print(type(Tuple_3))

#Converting to dictionary
Dict_1=dict(Tuple_3)
print(Dict_1)

#Type of object
print(type(Dict_1))

(('I', 'am'), ('Tuple', 'coverted'), ('to', 'Dictionary'))
<type 'tuple'>
{'I': 'am', 'to': 'Dictionary', 'Tuple': 'coverted'}
<type 'dict'>


### 2.Convert List to

#### [a]Tuple

In [60]:
#Initialising a List
List_1 = ['I','am','List','coverted','to','Tuple']
print(List_1)

#Type of object
print(type(List_1))

#Converting to tuple
Tuple_1= tuple(List_1)
print(Tuple_1)

#Type of object
print(type(Tuple_1))

['I', 'am', 'List', 'coverted', 'to', 'Tuple']
<type 'list'>
('I', 'am', 'List', 'coverted', 'to', 'Tuple')
<type 'tuple'>


#### [b]Set

In [61]:
#Initialising a List
List_2 = ['I','am','List','coverted','to','Set']
print(List_2)

#Type of object
print(type(List_2))

#Converting to set
Set_1 = set(List_2)
print Set_1

#Type of object
print(type(Set_1))
Set_1

['I', 'am', 'List', 'coverted', 'to', 'Set']
<type 'list'>
set(['Set', 'I', 'am', 'List', 'to', 'coverted'])
<type 'set'>


{'I', 'List', 'Set', 'am', 'coverted', 'to'}

#### [c]Dictionary

In [63]:
#Initialising a List
List_3 = [['I','am'],['List','coverted'],['to','Dictionary']]
print(List_3)

#Type of object
print(type(List_3))

#Converting to dictionary
Dict_1=dict(List_3)
print(Dict_1)

#Type of object
print(type(Dict_1))

[['I', 'am'], ['List', 'coverted'], ['to', 'Dictionary']]
<type 'list'>
{'I': 'am', 'to': 'Dictionary', 'List': 'coverted'}
<type 'dict'>


### 3.Convert Set to

#### [a]List

In [66]:
#Initialising a Set
Set_1 = {'I','am','Set','coverted','to','list'}
print(Set_1)

#Type of object
print(type(Set_1))

#Converting to list
List_1= list(Set_1)
print(List_1)

#Type of object
print(type(List_1))
Set_1

set(['Set', 'I', 'list', 'am', 'to', 'coverted'])
<type 'set'>
['Set', 'I', 'list', 'am', 'to', 'coverted']
<type 'list'>


{'I', 'Set', 'am', 'coverted', 'list', 'to'}

#### [b] Tuple

In [67]:
#Initialising a Set
Set_2 = {'I','am','Set','coverted','to','tuple'}
print(Set_2)

#Type of object
print(type(Set_2))

#Converting to tuple
Tuple_1= tuple(Set_2)
print(Tuple_1)

#Type of object
print(type(Tuple_1))
Set_2

set(['Set', 'tuple', 'I', 'am', 'to', 'coverted'])
<type 'set'>
('Set', 'tuple', 'I', 'am', 'to', 'coverted')
<type 'tuple'>


{'I', 'Set', 'am', 'coverted', 'to', 'tuple'}

#### [c]Dictionary

In [71]:
#Initialising a Set
Set_3 = {'I','am' ,'List','coverted','to','Dictionary'}
print(Set_3)

#Type of object
print(type(Set_3))

#Converting to dictionary
Dict_1=dict.fromkeys(Set_3,'values')
print(Dict_1)

#Type of object
print(type(Dict_1))

set(['Dictionary', 'I', 'List', 'am', 'to', 'coverted'])
<type 'set'>
{'to': 'values', 'coverted': 'values', 'Dictionary': 'values', 'I': 'values', 'am': 'values', 'List': 'values'}
<type 'dict'>


### 4.Convert Dictionary to 

#### [a]List

In [81]:
#Initialising a Dictionary
Dict_1 = {'I':'am','Dictionary':'converted','to':'List'}
print(Dict_1)

#Type of object
print(type(Dict_1))
List_1= list(Dict_1.items())  ## It is a tuple of list
print(List_1)

#Type of object
print(type(List_1))

#Converting to list
list_actual=[]
[list_actual.extend([key,value]) for key,value in Dict_1.items()]
print(list_actual)

#Type of object
print(type(list_actual))

{'I': 'am', 'to': 'List', 'Dictionary': 'converted'}
<type 'dict'>
[('I', 'am'), ('to', 'List'), ('Dictionary', 'converted')]
<type 'list'>
['I', 'am', 'to', 'List', 'Dictionary', 'converted']
<type 'list'>


#### [a]Tuple

In [86]:
#Initialising a Dictionary
Dict_2 = {'I':'am','Dictionary':'converted','to':'Tuple'}
print(Dict_2)

#Type of object
print(type(Dict_2))


Tuple_1= tuple(Dict_1.items())  ##Tuple of tuples
print(Tuple_1)

#Type of object
print(type(Tuple_1))

{'I': 'am', 'to': 'Tuple', 'Dictionary': 'converted'}
<type 'dict'>
(('I', 'am'), ('to', 'List'), ('Dictionary', 'converted'))
<type 'tuple'>


#### [c]set

In [88]:
#Initialising a Dictionary
Dict_3 = {'I':'am','Dictionary':'converted','to':'Tuple'}
print(Dict_3)

#Type of object
print(type(Dict_3))


Set_1= set(Dict_1.items())  ##Tuple of tuples
print(Set_1)

#Type of object
print(type(Set_1))
Set_1

{'I': 'am', 'to': 'Tuple', 'Dictionary': 'converted'}
<type 'dict'>
set([('Dictionary', 'converted'), ('to', 'List'), ('I', 'am')])
<type 'set'>


{('Dictionary', 'converted'), ('I', 'am'), ('to', 'List')}

### 5.Operations on List

In [168]:
#Initialising a List
list_lt = ['I','am','list','declared','using','square','brackets']
print(list_lt)

list_lt.append('I_am_Mutable')  # Appending an element to the list
print(list_lt)

x = list_lt.pop()  # pop , deletes newly added element or element from end
print(x)

del list_lt[3:7]  # deleting element from index 3 (inclusive) to index 7 (exclusive)
print(list_lt)

['I', 'am', 'list', 'declared', 'using', 'square', 'brackets']
['I', 'am', 'list', 'declared', 'using', 'square', 'brackets', 'I_am_Mutable']
I_am_Mutable
['I', 'am', 'list']


In [167]:
#Initialising a List
list_lt2 = [1,5,3,2,4]
print(list_lt2)

list_lt2.insert(5,9)  # Inserting a new element at index 5
print(list_lt2)

list_lt2.remove(9)  # removing the newly added element
print(list_lt2)

list_lt2.sort() # sort ascending order
print(list_lt2)

list_lt2.reverse() # sort descending order
print(list_lt2)

[1, 5, 3, 2, 4]
[1, 5, 3, 2, 4, 9]
[1, 5, 3, 2, 4]
[1, 2, 3, 4, 5]
[5, 4, 3, 2, 1]


### 6.Operations on Tuple

In [178]:
#Initialising a Tuple
tuple_tl = ('I','am','tuple','declared','using','round','brackets')
print(tuple_tl)

tuple_tl = tuple_tl + (19 ,)  # Inserting a new element at the end, .append() wont work as tuple is immutable
print(tuple_tl)
'''
.append() , .sort() ,.insert() ,.remove() methods wont work with tuple as it is immutable

'''

('I', 'am', 'tuple', 'declared', 'using', 'round', 'brackets')
('I', 'am', 'tuple', 'declared', 'using', 'round', 'brackets', 19)


'\n.append() , .sort() ,.insert() ,.remove() methods wont work with tuple as it is immutable\n\n'

### 7.Operations on Set

In [190]:
#Initialising a Set
set_st = {'I','am','set','declared','using','curly','brackets'}
print(set_st)

set_st.add('I_am_unordered')  #add item
print(set_st)

set_st.update(['I_am','distinct'])  #adding more than 1 item
print(set_st)

set_st.remove('distinct')   
print(set_st)

set_st.update('unique') #this will add individual
print(set_st)

set_st.pop()
print(set_st)


set(['declared', 'set', 'curly', 'brackets', 'I', 'am', 'using'])
set(['declared', 'set', 'curly', 'brackets', 'I', 'am', 'I_am_unordered', 'using'])
set(['declared', 'set', 'curly', 'brackets', 'I', 'am', 'I_am', 'I_am_unordered', 'using', 'distinct'])
set(['declared', 'set', 'curly', 'brackets', 'I', 'am', 'I_am', 'I_am_unordered', 'using'])
set(['declared', 'set', 'e', 'i', 'curly', 'brackets', 'I', 'am', 'I_am', 'n', 'q', 'I_am_unordered', 'u', 'using'])
set(['set', 'e', 'i', 'curly', 'brackets', 'I', 'am', 'I_am', 'n', 'q', 'I_am_unordered', 'u', 'using'])


### 8.Operations on Dictionary

In [252]:
#Initialising a Dictionary
Dict_1 ={'Student Name': 'Fredy', 'Roll No.': 12, 'Subject': 'English'}
print(Dict_1)

Dict_1.update({"Marks" : "100"})
print(Dict_1)

Dict_1['class'] ='MS_2nd_year' # Add a specific element
print(Dict_1)

Dict_1.pop('class') # Delete a specific element
print(Dict_1)

print(Dict_1.popitem()) # Delete an random element
print(Dict_1)

del Dict_1['Marks'] # Remove a specific element
print(Dict_1)

Dict_1.clear() # Delete all elements from the dictionary
print(Dict_1)

'''
del Dict_1    # Finally, eliminate the dictionary object
print(Dict_1)
'''

{'Roll No.': 12, 'Student Name': 'Fredy', 'Subject': 'English'}
{'Roll No.': 12, 'Student Name': 'Fredy', 'Marks': '100', 'Subject': 'English'}
{'Roll No.': 12, 'Student Name': 'Fredy', 'Marks': '100', 'class': 'MS_2nd_year', 'Subject': 'English'}
{'Roll No.': 12, 'Student Name': 'Fredy', 'Marks': '100', 'Subject': 'English'}
('Roll No.', 12)
{'Student Name': 'Fredy', 'Marks': '100', 'Subject': 'English'}
{'Student Name': 'Fredy', 'Subject': 'English'}
{}


'\ndel Dict_1    # Finally, eliminate the dictionary object\nprint(Dict_1)\n'

### 9.Copy of list , tuple and dictionary

In [277]:
import copy
#Initialising a list
List_1 = ['I','am','list']
print(List_1)
print(type(List_1))

List_2 = copy.copy(List_1) #Making a copy of original list
print(List_2)

List_1.append('original') #Change not reflected in copy, true copy
print(List_1)
print(List_2)

['I', 'am', 'list']
<type 'list'>
['I', 'am', 'list']
['I', 'am', 'list', 'original']
['I', 'am', 'list']


In [281]:
#Initialising a tuple
Tuple_1 = ('I','am','Tuple')
print(Tuple_1)

Tuple_2 = copy.copy(Tuple_1) #Making a copy of original tuple
print(Tuple_2)

Tuple_1=Tuple_1 + ('origial' ,)  # Inserting a new element
print(Tuple_1) #Change not reflected in copy, true copy
print(Tuple_2)

('I', 'am', 'Tuple')
('I', 'am', 'Tuple')
('I', 'am', 'Tuple', 'origial')
('I', 'am', 'Tuple')


In [299]:
#Initialising a Dictionary
Dict_1 = {'I':'am','Dict_1':'original'}
print(Dict_1)

Dict_2=Dict_1.copy()
print(Dict_2)

Dict_1.update({"Dict_2" : "Copy"}) # Inserting a new key value pair
print(Dict_1)  #Change not reflected in copy, true copy
print(Dict_2)

{'I': 'am', 'Dict_1': 'original'}
{'I': 'am', 'Dict_1': 'original'}
{'I': 'am', 'Dict_2': 'Copy', 'Dict_1': 'original'}
{'I': 'am', 'Dict_1': 'original'}


### 10. A function which accept input from keyboard and check if student grade should be First division, second division or Fail  

In [442]:
def read_scores():
    print("ENTER EXAM SCORE: ")
    exam = int(input())
    return exam

def grade_cal(exam):
    if(80 <= exam <=100):
        grade ='First_Division'
    elif(40 <= exam <=79):
        grade ='Second_Division'
    else:
        grade ='Failed'
    return grade


exam = read_scores()
grade = grade_cal(exam)
print("You got " + grade)



ENTER EXAM SCORE: 
90
You got First_Division


### 11. Operation on sets  

In [428]:
teamA = {'India', 'Australia','Pakistan', 'England'}
teamB = {'Bangladesh', 'New Zealand', 'West Indies', 'India'}
print(teamA)
print(teamB)

set(['Pakistan', 'Australia', 'England', 'India'])
set(['West Indies', 'New Zealand', 'India', 'Bangladesh'])


### 12. Add, clear, copy, difference, differenc_update(), discard, intersection

In [429]:
teamA.add('Srilanka')  ##Added a new element
print(teamA)

teamC= teamA.copy()    ##Copied the contents of set to a new set
print(teamC)

teamC.clear()  ##clearing the elements of the set
print(teamC)

teamC = teamA.intersection(teamB)   ##finding the common element
print(teamC)

teamA.intersection_update(teamB)   ##finding the common element and updating the  LHS
print(teamA)

teamD= teamB.difference(teamA) ##finding the difference 
print(teamD)

teamB.difference_update(teamA) ##finding the difference and updating the LHS
print(teamB)

teamD.discard('Bangladesh')  ##discarding one element
print(teamD)


set(['Pakistan', 'Australia', 'England', 'India', 'Srilanka'])
set(['Pakistan', 'Australia', 'England', 'India', 'Srilanka'])
set([])
set(['India'])
set(['India'])
set(['West Indies', 'New Zealand', 'Bangladesh'])
set(['West Indies', 'New Zealand', 'Bangladesh'])
set(['West Indies', 'New Zealand'])


### 13. Union,Symmetric_difference,and remove element from a set

In [430]:
teamE = teamA.union(teamB) ## union of sets and updating
print(teamE)

teamF = teamE.symmetric_difference(teamB) ##A-B union B-A
print(teamF)

teamE.remove('India')  ##Removing an element
print(teamE)


set(['West Indies', 'New Zealand', 'India', 'Bangladesh'])
set(['India'])
set(['West Indies', 'New Zealand', 'Bangladesh'])


### 14.List Comprehension with examples

In [443]:
## Example 1) Printing squares of even numbers

# Initialize `numbers`
numbers = range(22) #excluding 22

# Create `list_of_even_squares ` 
list_of_even_squares = [n**2 for n in numbers if n%2==0]

# Print `list_of_even_squares `
print(list_of_even_squares )

## Example 2) Printing squares of odd numbers

# Create `list_of_odd_squares ` 
list_of_odd_squares = [n**2 for n in numbers if n%2!=0]

# Print `list_of_odd_squares `
print(list_of_odd_squares )


[0, 4, 16, 36, 64, 100, 144, 196, 256, 324, 400]
[1, 9, 25, 49, 81, 121, 169, 225, 289, 361, 441]


### 15.Difference between List and tuple , with examples

In [438]:
##########---------------  Example ---------------######

##Initialisin a list object
list_fruit = ['Grapes',"apple", "banana", "cherry"]
print(list_fruit)
print(type(list_fruit))
print(len(list_fruit))


list_fruit[2] = "Mango" #changig the value at index 2
print((list_fruit))

##Initialisin a tuple object
tuple_fruit = ( 'Grapes',"apple", "banana", "cherry")
print(tuple_fruit)
print(type(tuple_fruit))
print(len(tuple_fruit))

tuple_fruit[2] = "Mango" #changig the value at index 2
print((tuple_fruit))

tuple_fruit[4] = "Guava" #Adding a value at index 4
print((tuple_fruit))

['Grapes', 'apple', 'banana', 'cherry']
<type 'list'>
4
['Grapes', 'apple', 'Mango', 'cherry']
('Grapes', 'apple', 'banana', 'cherry')
<type 'tuple'>
4


TypeError: 'tuple' object does not support item assignment

### 16.Output of the code snippet

In [444]:
if 1 and 0:
    print("Sucess 1 and 0")
elif 0 and 0:
    print("Sucess 0 and 0")
elif 0 and 1 or 1:
    print("Sucess 0 and 1 or 1")
elif 0 and 0 or 1 and 1:
    print("Sucess : 0 and 0 or 1 and 1")
    

Sucess 0 and 1 or 1


### 17.Output of the code snippet

In [446]:
list_of_lists = [[10, 20, 30], [40, 50, 60], [70, 80, 90]]
for list1 in list_of_lists: 
    for x in list1: 
        print(x)
    print(list1)


10
20
30
[10, 20, 30]
40
50
60
[40, 50, 60]
70
80
90
[70, 80, 90]


### 18.Numpy version

In [447]:
import numpy as np
print(np.__version__)
#print(np.show_config())

1.16.2


### 19.Vector with values ranging from 10 to 29

In [216]:
np_vector = np.arange(10,30) #30 is exclusive
print(np_vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


### 20.A 3x3 matrix with values ranging from 0 to 8 

In [217]:
np_matrix =  np.arange(0,9)  #9 is exclusive
print(np_matrix.reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 21.A 10x10 array with random values and find the minimum and maximum values

In [223]:
np_random = np.random.random((10,10))
print(np_random)
print(np_random.shape)
xmin, xmax =np_random.min(), np_random.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

[[0.48849932 0.48295009 0.1862891  0.49730112 0.48271594 0.32423801
  0.74984062 0.30162055 0.80027576 0.84922312]
 [0.75437996 0.03491433 0.88002944 0.31800864 0.50080699 0.47543189
  0.64895095 0.13491355 0.92475017 0.63366733]
 [0.3035969  0.49742358 0.39787596 0.30408067 0.07774788 0.77274788
  0.82039723 0.03534079 0.70623693 0.91027797]
 [0.56930384 0.66596849 0.43367731 0.80000035 0.89946644 0.08139321
  0.55930636 0.9630846  0.35899664 0.7842288 ]
 [0.35379109 0.11431223 0.73724198 0.64175766 0.60988249 0.60275835
  0.21945657 0.49294446 0.58338113 0.01636247]
 [0.39975168 0.48181206 0.6559679  0.00487212 0.45941762 0.68181264
  0.60307964 0.51187181 0.20056329 0.31420588]
 [0.65403674 0.85228042 0.41999992 0.87729971 0.49941947 0.38482463
  0.71434479 0.68544559 0.77359298 0.70954281]
 [0.22396805 0.35461525 0.88498166 0.55998607 0.81779881 0.18472794
  0.31185486 0.09004121 0.38087971 0.78373972]
 [0.31701952 0.22490823 0.7118107  0.16517926 0.54627729 0.91771556
  0.44025643

### 22.A random vector of size 30 and find the mean and median value 

In [232]:
np_vector = np.random.random(30)
print(np_vector)
print(" Mean is :", np_vector.mean())
print(" Median is :", np.median(np_vector))

[0.42136409 0.66015817 0.49841743 0.50307081 0.28725798 0.74135673
 0.45546244 0.34346057 0.65484164 0.51749585 0.48272131 0.22440349
 0.40797879 0.49308972 0.80678841 0.32130175 0.01656697 0.36370785
 0.55633609 0.71123206 0.02953308 0.91824893 0.98090119 0.60623236
 0.14152561 0.22882106 0.171874   0.36232487 0.2001259  0.34068074]
(' Mean is :', 0.4482426629855501)
(' Median is :', 0.43841326390835045)


### 23.An array and find the max value and index of max value

In [236]:
numpy_arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(numpy_arr)
minElement = np.amin(numpy_arr) 
print('Minimum element from Numpy Array : ', minElement)
maxElement= np.amax(numpy_arr)
print('Maximum element from Numpy Array :', maxElement)

[ 1  2  3  4  5  6  7  8  9 10]
('Minimum element from Numpy Array : ', 1)
('Maximum element from Numpy Array :', 10)


### 24.How to find the memory size of any array

In [239]:
print('The memory size of numpy_arr :',numpy_arr.size)


('The memory size of numpy_arr :', 10)


### 25. A 3x3 identity matrix 

In [233]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])